enum {
    COLOR_BACKGROUND,
    COLOR_AVATAR,
    COLOR_AVATAR_BORDER1,
    COLOR_AVATAR_BORDER2,
    COLOR_TUBE_DEFAULT,
    COLOR_TUBE_SHADOW,
    COLOR_TUBE_DEATH,
    COLOR_TUBE_PLATFORM,
    COLOR_TUBE_TOGGLE,
    COLOR_TUBE_BLUE,
    COLOR_TUBE_RED,
};

Color get_color(int clr);
